"use client";

import Link from "next/link";
import { ExternalLink, LoaderCircle } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { readContract, type Proposal } from "@/lib/rootguard";
import { ProposalActions } from "@/components/proposal-actions";

const stages = ["AWAITING_REVIEW", "APPROVED_CHALLENGE_WINDOW", "CHALLENGED", "EXECUTION_QUEUED", "EXECUTED"];
export function ProposalDetail({ id }: { id: string }) {
  const [proposal, setProposal] = useState<Proposal>(); const [error, setError] = useState<string>();
  const refresh = useCallback(async () => { try { setError(undefined); setProposal(await readContract<Proposal>("get_proposal", [id])); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load proposal."); } }, [id]);
  useEffect(() => { void refresh(); }, [refresh]);
  if (error) return <section className="rg-section"><p className="rg-alert">{error}</p><Link href="/proposals">Return to proposals</Link></section>;
  if (!proposal) return <section className="rg-section"><p><LoaderCircle className="spin"/> Reading live proposal...</p></section>;
  const activeIndex = stages.indexOf(String(proposal.status));
  return <><section className="page-intro"><p className="eyebrow">PROPOSAL LIFECYCLE</p><Link href="/proposals" className="back-link">Back to proposals</Link><h1>{String(proposal.id)}</h1><p className="lede">This page reads the selected proposal directly from the deployed RootGuard contract.</p><span className="badge amber">{String(proposal.status)}</span></section><section className="rg-section"><div className="timeline">{stages.map((stage, index) => <div key={stage} className={index <= activeIndex || String(proposal.status) === stage ? "timeline-step active" : "timeline-step"}><span>{index + 1}</span><strong>{stage.replaceAll("_", " ")}</strong></div>)}</div><div className="detail-grid"><article className="rg-card"><h2>Review record</h2><dl className="detail-list"><dt>Target</dt><dd>{String(proposal.target_id)}</dd><dt>Base version</dt><dd>{String(proposal.base_version)}</dd><dt>Proposed version</dt><dd>{String(proposal.proposed_version)}</dd><dt>Verdict</dt><dd>{String(proposal.verdict)}</dd><dt>Confidence</dt><dd>{String(proposal.confidence)}</dd><dt>Base source SHA</dt><dd><code>{String(proposal.base_source_sha256)}</code></dd><dt>Candidate SHA</dt><dd><code>{String(proposal.candidate_sha256 || "Pending review")}</code></dd></dl></article><article className="rg-card"><h2>Safety findings</h2><dl className="detail-list"><dt>Storage compatible</dt><dd>{String(proposal.storage_compatible)}</dd><dt>Authority preserved</dt><dd>{String(proposal.upgrade_authority_preserved)}</dd><dt>Value movement safe</dt><dd>{String(proposal.value_movement_safe)}</dd><dt>External calls safe</dt><dd>{String(proposal.external_calls_safe)}</dd><dt>Charter compliant</dt><dd>{String(proposal.charter_compliant)}</dd><dt>Critical risk</dt><dd>{String(proposal.critical_risk)}</dd><dt>Risk flags</dt><dd>{String(proposal.risk_flags || "[]")}</dd></dl></article><article className="rg-card"><h2>Evidence and challenge</h2><p>{String(proposal.rationale || "Awaiting consensus review.")}</p><a href={String(proposal.candidate_source_url)} target="_blank" rel="noreferrer">Candidate source <ExternalLink size={13}/></a><dl className="detail-list"><dt>Challenge deadline</dt><dd>{String(proposal.challenge_deadline || "Not set")}</dd><dt>Challenge used</dt><dd>{String(proposal.challenge_used)}</dd><dt>Challenge evidence</dt><dd>{String(proposal.challenge_url || "None")}</dd></dl></article></div><ProposalActions proposal={proposal} onFinalized={refresh}/></section></>;
}
