"use client";

import { useState } from "react";
import type { Proposal } from "@/lib/rootguard";
import { useWalletAction } from "@/components/wallet-action";
import { TransactionList } from "@/components/transaction-list";

export function ProposalActions({ proposal, onFinalized }: { proposal: Proposal; onFinalized: () => Promise<void> }) {
  const [url, setUrl] = useState(""); const [summary, setSummary] = useState("");
  const { error, transactions, send } = useWalletAction(onFinalized);
  const id = String(proposal.id); const status = String(proposal.status);
  const challengeOpen = proposal.challenge_deadline ? Date.now() < Date.parse(String(proposal.challenge_deadline)) : true;
  const button = (label: string, fn: string, note: string) => <div className="action-card"><h3>{label}</h3><p>{note}</p><button onClick={() => void send(label, fn, [id])}>{label}</button></div>;
  return <section className="proposal-actions"><p className="eyebrow">STATE-AWARE ACTIONS</p><h2>Proposal controls</h2>{error && <p className="form-error">{error}</p>}{status === "AWAITING_REVIEW" && button("Start GenLayer review", "review_upgrade", "Validators will fetch and assess the current and candidate source.")}{status === "APPROVED_CHALLENGE_WINDOW" && <><form className="action-card" onSubmit={(event) => { event.preventDefault(); void send("Open challenge", "open_challenge", [id, url, summary]); }}><h3>Open challenge</h3><p>{proposal.challenge_used ? "This proposal has already used its one challenge." : "Available once, before the on-chain deadline."}</p><label>Evidence URL<input required disabled={Boolean(proposal.challenge_used) || !challengeOpen} type="url" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://..."/></label><label>Evidence summary<textarea required disabled={Boolean(proposal.challenge_used) || !challengeOpen} value={summary} onChange={(e) => setSummary(e.target.value)} placeholder="Specific evidence-backed concern"/></label><button disabled={Boolean(proposal.challenge_used) || !challengeOpen}>Open challenge</button></form>{challengeOpen ? <div className="action-card disabled-action"><h3>Queue upgrade</h3><p>Available after the challenge window closes. RootGuard enforces the deadline.</p><button disabled>Queue upgrade</button></div> : button("Queue upgrade", "execute_upgrade", "The challenge window has closed. RootGuard will re-fetch and SHA-check the candidate before queueing.")}</>}{status === "CHALLENGED" && button("Review challenge", "review_challenge", "Validators fetch the submitted evidence and reassess the candidate.")}{status === "EXECUTION_QUEUED" && button("Confirm installation", "confirm_execution", "Available after the protected target installs the queued upgrade.")}{status === "EXECUTED" && <div className="action-card complete-action"><h3>Installation confirmed</h3><p>RootGuard has read the protected target and recorded the upgrade as executed.</p></div>}{["REJECTED", "ABSTAINED", "STALE"].includes(status) && <div className="action-card disabled-action"><h3>No executable action</h3><p>This proposal is terminal: {status}.</p></div>}<TransactionList transactions={transactions}/></section>;
}
