"use client";

import { useCallback, useEffect, useState } from "react";
import { ExternalLink, LoaderCircle, RefreshCw, ShieldCheck, TriangleAlert } from "lucide-react";
import { CONTRACT_ADDRESS, addressUrl, loadLedger, txUrl, type Ledger, type Proposal, type Target, waitFinalized, writeContract, writeRootGuard } from "@/lib/rootguard";

type Tx = { hash: string; label: string; status: "SUBMITTED" | "FINALIZED" | "FAILED"; triggered: string[] };
const blank: Ledger = { summary: {}, targets: [], proposals: [] };
const charter = "Only approve upgrades that preserve the declared storage layout, keep RootGuard as the sole upgrade authority, retain public reads, avoid value movement, and expose the stated version truthfully.";

export function RootGuardConsole() {
  const [ledger, setLedger] = useState<Ledger>(blank); const [wallet, setWallet] = useState<`0x${string}`>(); const [error, setError] = useState<string>(); const [loading, setLoading] = useState(true); const [txs, setTxs] = useState<Tx[]>([]);
  const refresh = useCallback(async () => { setLoading(true); try { setError(undefined); setLedger(await loadLedger()); } catch (e) { setError(e instanceof Error ? e.message : "Unable to read RootGuard."); } finally { setLoading(false); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  async function connect() { try { if (!window.ethereum) throw new Error("No injected GenLayer-compatible wallet was found."); const accounts = await window.ethereum.request({ method: "eth_requestAccounts" }) as `0x${string}`[]; if (!accounts[0]) throw new Error("Wallet returned no account."); setWallet(accounts[0]); } catch (e) { setError(e instanceof Error ? e.message : "Wallet connection failed."); } }
  async function send(label: string, fn: string, args: never[], address = CONTRACT_ADDRESS) { try { if (!wallet) throw new Error("Connect the correct wallet first."); if (!address) throw new Error("RootGuard contract not configured."); const hash = await (address === CONTRACT_ADDRESS ? writeRootGuard(wallet, fn, args) : writeContract(address, wallet, fn, args)); setTxs((old) => [{ hash, label, status: "SUBMITTED", triggered: [] }, ...old]); const result = await waitFinalized(wallet, hash); setTxs((old) => old.map((tx) => tx.hash === hash ? { ...tx, status: "FINALIZED", triggered: result.triggered } : tx)); await refresh(); } catch (e) { const detail = e instanceof Error ? e.message : "Transaction failed."; setError(detail); setTxs((old) => old.map((tx) => tx.status === "SUBMITTED" ? { ...tx, status: "FAILED" } : tx)); } }
  return <main className="rg-shell"><header className="rg-header"><a className="rg-mark" href="#top"><ShieldCheck size={24}/><span>ROOTGUARD</span></a><nav><a href="#targets">Targets</a><a href="#proposals">Proposals</a><a href="#actions">Actions</a></nav><div className="rg-wallet">{wallet ? <><code>{wallet.slice(0, 8)}...{wallet.slice(-6)}</code><button onClick={() => setWallet(undefined)}>Disconnect</button></> : <button onClick={connect}>Connect wallet</button>}</div></header><section id="top" className="rg-hero"><div><p className="eyebrow">GENLAYER UPGRADE AUTHORITY</p><h1>Code changes need proof, not just permission.</h1><p className="lede">RootGuard turns source review, a challenge window, exact-byte binding, native upgrade authority, and installation confirmation into one on-chain control plane.</p><p className="rg-address">Network: StudioNet · {CONTRACT_ADDRESS ? <a href={addressUrl(CONTRACT_ADDRESS)} target="_blank">{CONTRACT_ADDRESS}<ExternalLink size={14}/></a> : "RootGuard contract not configured"}</p></div><div className="rg-grid stats">{Object.entries({"Targets":ledger.summary.target_count ?? "-", "Proposals":ledger.summary.proposal_count ?? "-", "Approved":ledger.summary.approved_count ?? "-", "Executed":ledger.summary.executed_count ?? "-"}).map(([k,v]) => <div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div></section>{error && <div className="rg-alert"><TriangleAlert size={18}/>{error}</div>}<section id="targets" className="rg-section"><h2>Protected targets <button className="icon-button" onClick={() => void refresh()}><RefreshCw size={16}/></button></h2>{loading ? <p><LoaderCircle className="spin"/> Reading live RootGuard state...</p> : ledger.targets.length ? <div className="rg-cards">{ledger.targets.map((t) => <TargetCard key={String(t.id)} target={t}/>)}</div> : <p className="rg-empty">No protected targets are enrolled on this RootGuard.</p>}<EnrollForm send={send}/></section><section id="proposals" className="rg-section"><h2>Upgrade proposals</h2>{ledger.proposals.length ? <div className="rg-cards">{ledger.proposals.map((p) => <ProposalCard key={String(p.id)} proposal={p}/>)}</div> : <p className="rg-empty">No proposals are on-chain.</p>}<ProposalForm targets={ledger.targets} send={send}/></section><section id="actions" className="rg-section"><h2>Proposal actions</h2><ActionForms send={send}/><div className="rg-txs">{txs.map((tx) => <div className="tx-row" key={tx.hash}><a href={txUrl(tx.hash)} target="_blank">{tx.label} <ExternalLink size={13}/></a><span className={`badge ${tx.status === "FINALIZED" ? "green" : "amber"}`}>{tx.status}</span>{tx.triggered.map((child) => <a key={child} href={txUrl(child)} target="_blank">child upgrade <ExternalLink size={13}/></a>)}</div>)}</div></section></main>;
}
function TargetCard({target}:{target:Target}) { return <article className="rg-card"><strong>{String(target.name)} · {String(target.current_version)}</strong><code>{String(target.contract_address)}</code><p>Steward: {String(target.steward)}</p><p>Source SHA: {String(target.current_source_sha256)}</p><a href={String(target.current_source_url)} target="_blank">Pinned source <ExternalLink size={13}/></a></article>; }
function ProposalCard({proposal}:{proposal:Proposal}) { return <article className="rg-card"><strong>{String(proposal.id)} <span className="badge amber">{String(proposal.status)}</span></strong><p>{String(proposal.base_version)} → {String(proposal.proposed_version)} · {String(proposal.verdict)} / {String(proposal.confidence)}</p><p>Candidate SHA: {String(proposal.candidate_sha256 || "pending")}</p><p>{String(proposal.rationale || "Awaiting consensus review.")}</p><a href={String(proposal.candidate_source_url)} target="_blank">Candidate source <ExternalLink size={13}/></a></article>; }
function EnrollForm({send}:{send:RootGuardConsoleProps["send"]}) { const [f,setF]=useState({id:"",name:"",target:"",source:"",charter}); return <form className="rg-form" onSubmit={e=>{e.preventDefault();void send("target enrollment","enroll_with_rootguard",[f.id,f.name,f.charter,f.source] as never[],f.target as `0x${string}`)}}><h3>Enroll through protected target</h3><p className="muted">Only the target owner can call this target method. RootGuard rejects direct wallet registration.</p><input required placeholder="target-id" value={f.id} onChange={e=>setF({...f,id:e.target.value})}/><input required placeholder="Target name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input required placeholder="Protected target address" value={f.target} onChange={e=>setF({...f,target:e.target.value})}/><input required type="url" placeholder="Commit-pinned current source URL" value={f.source} onChange={e=>setF({...f,source:e.target.value})}/><textarea value={f.charter} onChange={e=>setF({...f,charter:e.target.value})}/><button>Request secure enrollment</button></form>; }
type RootGuardConsoleProps={send:(label:string,fn:string,args:never[],address?:`0x${string}`)=>Promise<void>};
function ProposalForm({targets,send}:{targets:Target[];send:RootGuardConsoleProps["send"]}) { const [f,setF]=useState({id:"",target:"",source:"",version:"",summary:""}); return <form className="rg-form" onSubmit={e=>{e.preventDefault();void send("submit upgrade","submit_upgrade",[f.id,f.target,f.source,f.version,f.summary] as never[])}}><h3>Submit candidate</h3><input required placeholder="proposal-id" value={f.id} onChange={e=>setF({...f,id:e.target.value})}/><select required value={f.target} onChange={e=>setF({...f,target:e.target.value})}><option value="">Select target</option>{targets.map(t=><option key={String(t.id)} value={String(t.id)}>{String(t.name)}</option>)}</select><input required type="url" placeholder="Commit-pinned candidate source URL" value={f.source} onChange={e=>setF({...f,source:e.target.value})}/><input required placeholder="Proposed version" value={f.version} onChange={e=>setF({...f,version:e.target.value})}/><textarea required placeholder="Change summary (80+ characters)" value={f.summary} onChange={e=>setF({...f,summary:e.target.value})}/><button>Submit for consensus</button></form>; }
function ActionForms({send}:{send:RootGuardConsoleProps["send"]}) { const [id,setId]=useState(""); const [url,setUrl]=useState(""); const [summary,setSummary]=useState(""); const form=(title:string,fn:string,args:string[]) => <form className="inline-form" onSubmit={e=>{e.preventDefault();void send(title,fn,args as never[])}}><h3>{title}</h3><input required placeholder="proposal-id" value={id} onChange={e=>setId(e.target.value)}/>{fn==="open_challenge"&&<><input required type="url" placeholder="HTTPS evidence URL" value={url} onChange={e=>setUrl(e.target.value)}/><textarea required placeholder="Evidence summary" value={summary} onChange={e=>setSummary(e.target.value)}/></>}<button>{title}</button></form>; return <div className="actions">{form("Review","review_upgrade",[id])}{form("Open challenge","open_challenge",[id,url,summary])}{form("Review challenge","review_challenge",[id])}{form("Queue upgrade","execute_upgrade",[id])}{form("Confirm installation","confirm_execution",[id])}</div>; }
