"use client";
import Link from "next/link";
import { ExternalLink, LoaderCircle } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { addressUrl, readContract, type Target } from "@/lib/rootguard";
import { useWallet } from "@/components/wallet-provider";
import { useWalletAction } from "@/components/wallet-action";
import { TransactionList } from "@/components/transaction-list";

export function TargetDetail({ id }: { id: string }) {
  const [target, setTarget] = useState<Target>(); const [error, setError] = useState<string>(); const [account, setAccount] = useState("");
  const { address, profile } = useWallet();
  const refresh = useCallback(async () => { try { setError(undefined); setTarget(await readContract<Target>("get_target", [id])); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load target."); } }, [id]);
  useEffect(() => { void refresh(); }, [refresh]);
  const { error: actionError, transactions, send } = useWalletAction(refresh);
  if (error) return <section className="rg-section"><p className="rg-alert">{error}</p><Link href="/targets">Return to targets</Link></section>;
  if (!target) return <section className="rg-section"><p><LoaderCircle className="spin"/> Reading live target...</p></section>;
  const steward = address?.toLowerCase() === String(target.steward).toLowerCase(); const maintainer = Boolean(profile?.maintained_targets?.includes(id));
  return <><section className="page-intro"><p className="eyebrow">PROTECTED TARGET</p><Link className="back-link" href="/targets">Back to targets</Link><h1>{String(target.name)}</h1><p className="lede">{steward ? "You are the steward for this target." : maintainer ? "You are an authorized maintainer for this target." : "Live RootGuard target record."}</p><span className={`badge ${target.active ? "green" : "red"}`}>{target.active ? "ACTIVE" : "INACTIVE"}</span></section><section className="rg-section"><div className="detail-grid"><article className="rg-card"><h2>Target record</h2><dl className="detail-list"><dt>Target ID</dt><dd>{String(target.id)}</dd><dt>Current version</dt><dd>{String(target.current_version)}</dd><dt>Proposal count</dt><dd>{String(target.proposal_count)}</dd><dt>Active proposal</dt><dd>{String(target.active_proposal_id || "None")}</dd><dt>Steward</dt><dd><code>{String(target.steward)}</code></dd></dl></article><article className="rg-card"><h2>Authority and source</h2><dl className="detail-list"><dt>Protected target</dt><dd><a href={addressUrl(String(target.contract_address))} target="_blank" rel="noreferrer"><code>{String(target.contract_address)}</code> <ExternalLink size={12}/></a></dd><dt>RootGuard</dt><dd><a href={addressUrl(process.env.NEXT_PUBLIC_ROOTGUARD_CONTRACT ?? "")} target="_blank" rel="noreferrer">Open RootGuard <ExternalLink size={12}/></a></dd><dt>Current source SHA</dt><dd><code>{String(target.current_source_sha256)}</code></dd></dl><a href={String(target.current_source_url)} target="_blank" rel="noreferrer">Pinned current source <ExternalLink size={13}/></a></article></div><section className="proposal-actions"><p className="eyebrow">STEWARD CONTROLS</p><h2>Target management</h2>{actionError && <p className="form-error">{actionError}</p>}<form className="action-card" onSubmit={(event) => { event.preventDefault(); void send("Authorize maintainer", "set_maintainer", [id, account, true]); }}><h3>Manage maintainer</h3><p>Contract authorization remains authoritative. Only the steward can change maintainers.</p><label>Maintainer address<input required value={account} onChange={(event) => setAccount(event.target.value)} placeholder="0x..."/></label><div className="button-row"><button>Authorize maintainer</button><button type="button" className="quiet" onClick={() => void send("Remove maintainer", "set_maintainer", [id, account, false])}>Remove maintainer</button></div></form><div className="action-card danger-action"><h3>Deactivate target</h3><p>Deactivation stops new RootGuard upgrade proposals for this target. The contract rejects deactivation while a live proposal is unresolved.</p><button onClick={() => void send("Deactivate target", "deactivate_target", [id])} disabled={!target.active}>Deactivate target</button></div><TransactionList transactions={transactions}/></section></section></>;
}
